version: '3.6'
services:
  api:
    build:
      context: ./flask
    ports:
      - 80:80
    depends_on:
      - pg
  pg:
    build:
      context: ./postgres
    volumes:
      - ./postgres/init/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=piwik
      - POSTGRES_USER=piwik
      - POSTGRES_PASSWORD=piwik